# Redis 7 — configuración base para NEXUS
# La contraseña se pasa como argumento en docker-compose (--requirepass)

# Persistencia
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfsync everysec

# Memoria
maxmemory 256mb
maxmemory-policy allkeys-lru

# Red
bind 0.0.0.0
protected-mode no

# Logs
loglevel notice